version: '3.7'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "${APP_PORT}:5678"
    environment:
      - GENERIC_TIMEZONE=America/New_York
      - TZ=America/New_York
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n
    networks:
      - runtipi_network

networks:
  runtipi_network:
    external: true
