version: '3.7'
services:
  martin:
    image: maplibre/martin:v0.14.0
    container_name: martin
    command: ${DATABASE_URL}
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3000"
    networks:
      - runtipi_network

networks:
  runtipi_network:
    external: true
